### ISSUE TITLE
predictor 预测报错

### ISSUE THREAD

**Issue by songsh** [fastnlp/fastNLP#306]
我在用BertForQuestionAnswering 预测时，数据是这样准备的

def  prepare_fake_dataset():
    data_set = DataSet([Instance(title='',
    context='《战国无双3》（）是由光荣和ω-force开发的战国无双系列的正统第三续作。本作以三大故事为主轴，分别是以武田信玄等人为主的《关东三国志》，织田信长等人为主的《战国三杰》，石田三成等人为主的《关原的年轻武者》，丰富游戏内的剧情。此部份专门介绍角色，欲知武器情报、奥义字或擅长攻击类型等，请至战国无双系列1.由于乡里大辅先生因故去世，不得不寻找其他声优接手。从猛将传 and Z开始。2.战国无双 编年史的原创男女主角亦有专属声优。此模式是任天堂游戏谜之村雨城改编的新增模式。本作中共有20张战场地图（不含村雨城），后来发行的猛将传再新增3张战场地图。但游戏内战役数量繁多，部分地图会有兼用的状况，战役虚实则是以光荣发行的2本「战国无双3 人物真书」内容为主，以下是相关介绍。（注：前方加☆者为猛将传新增关卡及地图。）合并本篇和猛将传的内容，村雨城模式剔除，战国史模式可直接游玩。主打两大模式「战史演武」&「争霸演武」。系列作品外传作品'
    ,question='《战国无双3》是由哪两个公司合作开发的？')])
    return data_set

Traceback (most recent call last):
  File "fastNLP1.py", line 73, in <module>
    ans = predictor.predict(data)
  File "/home/songlovedu/.local/lib/python3.6/site-packages/fastNLP/core/predictor.py", line 64, in predict
    prediction = predict_func(**refined_batch_x)
TypeError: predict() missing 1 required positional argument: 'words'

words 要怎么写 ， 这还需要其它字段吗？

**Comment by yhcc** [comment]
pred_start取argmax得到start的index, pred_end也许argmax得到end的index; 然后再从raw_words中取出raw_words[start:end]这样。

**Comment by songsh** [comment]
感谢, 你这说的raw_words 就是我程序中 words 字段吧。

**Comment by yhcc** [comment]
argmax就是pytorch的argmax，tensor.argmax(dim=-1)这样，或者torch.argmax(tensor, dim=-1)

**Comment by songsh** [comment]
pend=torch.Tensor(ans['pred_end'])
pstart=torch.Tensor(ans['pred_start'])
print(torch.argmax(pend,dim=-1))
print(torch.argmax(pstart,dim=-1))

代码这么写的，
我问了两个问题，
返回结果都是 1,113 , 哪有问题?

**Comment by yhcc** [comment]
之前我说的做法有误，因为在阅读理解中一定不会出现end在start后面的情况。所以可以这样
```python
pend=torch.Tensor(ans['pred_end'])  # 应该是一个length长的vecctor
pstart=torch.Tensor(ans['pred_start'])

start = pstart.argmax(dim=-1)  
end = pend[start+1:].argmax(dim=-1)
```

不过全部预测1和113的问题应该不是这个导致的。你训练结束后em和f1分别是多少呢？

**Comment by songsh** [comment]
f1=86.52, em=66.85

**Comment by songsh** [comment]
pend=torch.Tensor(ans['pred_end'])  # 应该是一个length长的vecctor
pstart=torch.Tensor(ans['pred_start'])

start = pstart.argmax(dim=-1)  
end = pend[start+1:].argmax(dim=-1)
报错：
index 154 is out of bounds for dimension 0 with size 1
