### ISSUE TITLE
StaticEmbedding param vocab: Vocabulary. 若该项为None则会读取所有的embedding。

### ISSUE THREAD

**Issue by el-psy** [fastnlp/fastNLP#346]
from fastNLP.embeddings import StaticEmbedding
word2vec_embed=StaticEmbedding(None, model_dir_or_name='cn-char-fastnlp-100d')

Traceback (most recent call last):
  File "d:\data\node_with_att_bert_data_tunnel.py", line 175, in <module>
    word2vec_embed=StaticEmbedding(None, model_dir_or_name='cn-char-fastnlp-100d')
  File "E:\ProgramData\Anaconda3\lib\site-packages\fastNLP\embeddings\static_embedding.py", line 96, in __init__
    super(StaticEmbedding, self).__init__(vocab, word_dropout=word_dropout, dropout=dropout)
  File "E:\ProgramData\Anaconda3\lib\site-packages\fastNLP\embeddings\embedding.py", line 127, in __init__
    if vocab.rebuild:
AttributeError: 'NoneType' object has no attribute 'rebuild'

请问可否有其他的方法将embedding的所有字加载，或者直接生成对应的Vocabulary？

**Comment by yhcc** [comment]
抱歉，这是一个错误的文档说明。
目前只能通过自己写一下读取embedding的方式，我们最近会开发一下直接读取整个embedding的代码。
